apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: alpine
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"]

---

apiVersion: v1
kind: Service
metadata:
  name: alpine-service
spec:
  selector:
    app: alpine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
