apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp
    release: "0-5"

  ports:
    # Accept traffic sent to port 80
    # Node port (external)
    - name: http
      port: 80
      # targetPort: 80                  ## Use if using a Optional if same as port, this is the port on the pod
      nodePort: 30080               ## Need to use 30xxx
  #type: ClusterIP                     ## Defaults to ClusterIP. Type is clusterIP nodePort,  ExternalName, ClusterIP, NodePort, and LoadBalancer
  type: NodePort                     ## Defaults to ClusterIP. Type is clusterIP nodePort,  ExternalName, ClusterIP, NodePort, and LoadBalancer
