apiVersion: apps/v1               ## A different api version as apposed to pods 
kind: ReplicaSet
metadata:
  ## unigue name for replica set 
  name: webapp    ## dont need to have a complicate name with replica, when you get it will list as replica to keep names short 
spec:                    ## This spec is for the replica
  ## 1 pod up all the time
  replicas: 3
  selector:
    matchLabels:                 #Make sure you add this for the Replicaset 
      app: webapp
      release: "0"
## Everything under this is standard Pod definition 
  template:
    metadata:
      # name: webapp            ##Dont need a name as it is automaticall named by rep set
      labels:
        app: webapp                 ## this is the label for the APP, it will be used by selector in Service 
        release: "0"                ## this is the label for the APP version 
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-0-5
  labels:                       ## With multiple labels, if used by serivice, must use all 
    app: webapp                 ## this is the label for the APP, it will be used by selector in Service
    release: "0-5"              ## this is the label for the APP version 0-5 
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    #app: webapp                 ## this is the label for the APP, it will be used by selector in Service 
    #release: "0"                ## this is the label for the APP version 
    app: queue
    release: "1"
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1
