apiVersion: apps/v1
kind: Deployment
metadata:
  ## unigue name for Deployment 
  name: webapp    ## dont need to have a complicate name with replica, when you get it will list as replica to keep names short 
spec:                    ## This spec is for the replica
  minReadySeconds: 30
  selector:
    matchLabels:                 #Make sure you add this for the Replicaset 
      app: webapp
  replicas: 4
  template:
    metadata:
      labels:
        app: webapp                 ## this is the label for the APP, it will be used by selector in Service 
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0 #-5

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    #app: webapp                 ## this is the label for the APP, it will be used by selector in Service 
    #release: "0"                ## this is the label for the APP version 
    app: queue
    release: "1"
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1
